spring:
  application:
    name: ticketing-system

  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    consumer:
      group-id: ticketing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

ticketing:
  kafka:
    topic: ticket-reservation
